name 'workstation'
maintainer 'Victor Mendo'
maintainer_email 'victor.mendo@oracle.com'
license 'all_rights'
description 'Installs/Configures workstation'
long_description 'Installs/Configures workstation'
version '0.2.0'
